only-pre-branches: &only-pre-branches
  filters:
    tags:
      only: v1.1
#    branches:
#      only: /^pre.*/
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
  build:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: echo "build successful! "

workflows:
  version: 2
#  parallel:
#    jobs:
#      - test
#      - build
  serial:
    jobs:
      - test:
          <<: *only-pre-branches
      - build:
          <<: *only-pre-branches
#          requires:
#            - test

