version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
  build:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: echo "build successful! "

workflows:
  version: 2
#  parallel:
#    jobs:
#      - test
#      - build
  serial:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
                - dev2
      - build:
          filters:
            branches:
              only:
                - master
                - dev2
#          requires:
#            - test

