version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
  build:
    steps:
      - echo "build"

workflows:
  version: 2
  parallel:
    - test
    - build
  serial:
    - test
    - build:
        requires:
          - test
