only-pre-branches: &only-pre-branches
  filters:
    branches:
      only: master
#    branches:
#      only: /^pre.*/
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
  build:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: echo "build successful! "
  corn-test:
    docker:
      - image: circleci/node:12.0
    steps:
      - run: curl https://www.baidu.com
workflows:
  version: 2
#  parallel:
#    jobs:
#      - test
#      - build
  nightly:
    triggers:
      - schedule:
          corn: "* * * * *"
    jobs:
      - corn-test
  serial:
    jobs:
      - test:
          <<: *only-pre-branches
      - build:
          <<: *only-pre-branches
#          requires:
#            - test

